config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  get 'lists/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists do
    resources :bookmarks, only: [:new, :create]
  end
    resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  has_one_attached :photo
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: {scope: :list_id}
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, uniqueness: true, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    @bookmark.save
    redirect_to list_path(@list)
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save
    redirect_to lists_path
  end

end

private
def list_params
  params.require(:list).permit(:name, :photo)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>
  <%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.submit "Submit Bookmark" %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1>Welcome to the index of Lists</h1>
  <p>Check the list in here: </p>
  <%= cl_image_tag("https://res.cloudinary.com/dpoc03ecv/image/upload/v1653652232/gbzevdegc886huo2jjff.jpg",
      width: 400, height: 300, crop: :fill) %>
  <ul>
    <% @lists.each do |list| %>
      <li><%= link_to list.name, list %></li>
        <% if  list.photo.key %>
          <%= cl_image_tag list.photo.key, height: 200, width: 300, crop: :fill %>
          <% else %>
              <%= cl_image_tag("https://res.cloudinary.com/dpoc03ecv/image/upload/v1653652232/gbzevdegc886huo2jjff.jpg",
                width: 400, height: 300, crop: :fill) %>
        <% end %>
    <% end %>

  </ul>
  <br>
  <%= link_to "Create the link", new_list_path %>
  <br>
</div>

app/views/lists/new.html.erb
<h1>Creating new list</h1>

<%= simple_form_for @list do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "create the list" %>
<% end %>

app/views/lists/show.html.erb
<div class="container">
  <h2><span>List: </span><%= @list.name %></h2>
  <%= cl_image_tag @list.photo.key, height: 400, width: 500, crop: :fill %>
    <ol>
      <% @list.bookmarks.each do |bookmark| %>
      <li><h1>Comment:</h1><%= bookmark.comment %></li>
      <%= link_to "Click to Delete",
      bookmark_path(bookmark),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      <h1><%= bookmark.movie.title %></h1>
      <% end %>
    <ol>
  <br>
  <%= link_to "Add to bookmark", new_list_bookmark_path(@list) %>
  <%= link_to "Back to home", lists_path %>

</div>